import React from 'react';
import { Link } from 'react-router-dom';
import {
  Globe,
  MapPin,
  Layers,
  Sliders,
  TrendingUp,
  BookOpen,
  ArrowRight,
  ShieldCheck,
  AlertOctagon,
  Sparkles,
  Compass,
  CheckCircle2,
} from 'lucide-react';

export const HomePage: React.FC = () => {
  return (
    <div className="space-y-24 py-6">
      {/* 1. HERO SECTION */}
      <section className="relative pt-8 pb-12 overflow-hidden text-center max-w-5xl mx-auto px-4">
        {/* Background Glowing Orb */}
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-96 h-96 bg-emerald-500/10 blur-[120px] rounded-full pointer-events-none -z-10"></div>
        <div className="absolute top-1/3 right-1/4 w-72 h-72 bg-cyan-500/10 blur-[100px] rounded-full pointer-events-none -z-10"></div>

        {/* Badge */}
        <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-slate-900 border border-slate-700/80 text-xs font-semibold mb-6 shadow-sm">
          <span className="w-2 h-2 rounded-full bg-emerald-400 animate-ping"></span>
          <span className="text-emerald-400 font-bold">GRAIN</span>
          <span className="text-slate-500">·</span>
          <span className="text-slate-300">Spatial Econometrics & Agrifood Systems Research</span>
        </div>

        {/* Title */}
        <h1 className="text-4xl sm:text-6xl font-extrabold tracking-tight text-white leading-tight">
          Anatomy of ASEAN Agrifood System Emissions:{' '}
          <span className="bg-gradient-to-r from-emerald-400 via-teal-300 to-cyan-400 bg-clip-text text-transparent">
            Detecting Spatial Hotspots & Cross-Border Leakage
          </span>
        </h1>

        {/* Subtitle */}
        <p className="mt-6 text-base sm:text-lg text-slate-300 max-w-3xl mx-auto leading-relaxed">
          Dissecting balanced panel dynamics across <strong className="text-white">44 Asia-Pacific economies over 64 years (1961–2024)</strong> via non-parametric clustering, Moran's I spatial autocorrelation, and the <strong className="text-white">Spatial Durbin Model (SDM)</strong>.
        </p>

        {/* Action Buttons */}
        <div className="mt-8 flex flex-wrap items-center justify-center gap-4">
          <Link
            to="/clustering"
            className="px-6 py-3 rounded-xl bg-emerald-500 text-slate-950 font-bold text-sm hover:bg-emerald-400 transition-all shadow-lg shadow-emerald-500/20 flex items-center gap-2"
          >
            <MapPin className="w-4 h-4" />
            <span>Explore Maps & 5 Clusters</span>
            <ArrowRight className="w-4 h-4" />
          </Link>
          <Link
            to="/spasial"
            className="px-6 py-3 rounded-xl bg-slate-900 text-slate-200 border border-slate-700 font-semibold text-sm hover:bg-slate-800 transition-colors flex items-center gap-2"
          >
            <Layers className="w-4 h-4 text-cyan-400" />
            <span>View Econometric Evidence</span>
          </Link>
          <Link
            to="/simulator"
            className="px-6 py-3 rounded-xl bg-slate-900 text-slate-200 border border-slate-700 font-semibold text-sm hover:bg-slate-800 transition-colors flex items-center gap-2"
          >
            <Sliders className="w-4 h-4 text-amber-400" />
            <span>Spillover Simulator</span>
          </Link>
        </div>

        {/* 4 Stat Highlights */}
        <div className="mt-14 grid grid-cols-2 md:grid-cols-4 gap-4 text-left">
          <div className="p-4 rounded-xl bg-slate-900/60 border border-slate-800 backdrop-blur-sm">
            <span className="text-[11px] font-bold text-red-400 uppercase tracking-wider block">
              Global Land-Use Share
            </span>
            <p className="text-2xl font-black text-white font-mono mt-1">22.78%</p>
            <p className="text-xs text-slate-400 mt-1">
              Global agricultural land-use change emissions generated by ASEAN (2024).
            </p>
          </div>

          <div className="p-4 rounded-xl bg-slate-900/60 border border-slate-800 backdrop-blur-sm">
            <span className="text-[11px] font-bold text-amber-400 uppercase tracking-wider block">
              Typology Concentration
            </span>
            <p className="text-2xl font-black text-white font-mono mt-1">7 of 10</p>
            <p className="text-xs text-slate-400 mt-1">
              ASEAN member economies cluster in the Land Conversion Frontier.
            </p>
          </div>

          <div className="p-4 rounded-xl bg-slate-900/60 border border-slate-800 backdrop-blur-sm">
            <span className="text-[11px] font-bold text-emerald-400 uppercase tracking-wider block">
              Global Moran's I
            </span>
            <p className="text-2xl font-black text-white font-mono mt-1">+0.729</p>
            <p className="text-xs text-slate-400 mt-1">
              Strong spatial autocorrelation in land-use emissions (p = 0.002).
            </p>
          </div>

          <div className="p-4 rounded-xl bg-slate-900/60 border border-slate-800 backdrop-blur-sm">
            <span className="text-[11px] font-bold text-cyan-400 uppercase tracking-wider block">
              Synthetic N₂O Spillover
            </span>
            <p className="text-2xl font-black text-white font-mono mt-1">&gt;2× Domestic</p>
            <p className="text-xs text-slate-400 mt-1">
              Indirect spillover (+1.1046) exceeds direct domestic impact (+0.5011).
            </p>
          </div>
        </div>
      </section>

      {/* 2. STORYTELLING: 4 BABAK NARASI UTAMA */}
      <section className="max-w-6xl mx-auto px-4 space-y-12">
        <div className="text-center space-y-2">
          <span className="text-xs font-bold uppercase tracking-wider px-3 py-1 rounded-full bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
            Scroll Storytelling
          </span>
          <h2 className="text-3xl font-extrabold text-white tracking-tight">
            Four Analytical Acts: The ASEAN Agrifood Investigation
          </h2>
          <p className="text-sm text-slate-400 max-w-2xl mx-auto">
            Tracing systemic linkages across agricultural land expansion, synthetic nitrogen inputs, and cross-border econometric spillovers.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {/* Babak 1 */}
          <div className="p-6 rounded-2xl bg-slate-900/60 border border-slate-800 hover:border-slate-700 transition-all flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between mb-3">
                <span className="text-xs font-mono font-bold text-emerald-400 bg-emerald-950/60 px-2.5 py-1 rounded border border-emerald-800/60">
                  ACT 01
                </span>
                <span className="text-xs text-slate-500 font-mono">The Regional Imbalance</span>
              </div>
              <h3 className="text-xl font-bold text-white mb-2">
                Ecological Asymmetry: Global Footprint vs. Domestic Intensity
              </h3>
              <p className="text-sm text-slate-300 leading-relaxed mb-4">
                ASEAN accounts for <strong className="text-white">7.44%</strong> of global aggregate Greenhouse Gases (GHG), yet shoulders a disproportionate <strong className="text-red-400">22.78%</strong> of global agricultural land-use change emissions in 2024. Indonesia alone generates <strong className="text-white">12.57%</strong> of worldwide land-use emissions.
              </p>
              <div className="p-3 bg-slate-950 rounded-xl border border-slate-800 text-xs text-slate-400">
                <strong className="text-slate-200">Spearman Paradox:</strong> Rank correlation between per-capita emission intensity and global cumulative share is essentially zero (<strong className="text-emerald-400">0.008</strong>). Economies pivotal to planetary climate stability are decoupled from per-capita emission rankings.
              </div>
            </div>
          </div>

          {/* Babak 2 */}
          <div className="p-6 rounded-2xl bg-slate-900/60 border border-slate-800 hover:border-slate-700 transition-all flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between mb-3">
                <span className="text-xs font-mono font-bold text-amber-400 bg-amber-950/60 px-2.5 py-1 rounded border border-amber-800/60">
                  ACT 02
                </span>
                <span className="text-xs text-slate-500 font-mono">44-Economy Typology</span>
              </div>
              <h3 className="text-xl font-bold text-white mb-2">
                Structural Agrifood Coherence: The Frontier Dominance
              </h3>
              <p className="text-sm text-slate-300 leading-relaxed mb-4">
                Across 864 grid search specifications, K-Means (k=5) yields the optimal cluster structure (Silhouette <strong className="text-white">0.5336</strong>, ARI stability <strong className="text-white">0.973</strong>). Seven ASEAN economies—Indonesia, Vietnam, Thailand, Cambodia, Laos, Myanmar, and Malaysia—coalesce into an identical cluster: <strong className="text-red-400">Land Conversion Frontier</strong>.
              </p>
              <div className="p-3 bg-slate-950 rounded-xl border border-slate-800 text-xs text-slate-400">
                <strong className="text-slate-200">Three Structural Exceptions:</strong> Singapore (Established Land-Sparing Industrial), Philippines (High-Density Low-Intensity Agrarian), and Brunei (Extensive Pastoral & Extraction).
              </div>
            </div>
          </div>

          {/* Babak 3 */}
          <div className="p-6 rounded-2xl bg-slate-900/60 border border-slate-800 hover:border-slate-700 transition-all flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between mb-3">
                <span className="text-xs font-mono font-bold text-cyan-400 bg-cyan-950/60 px-2.5 py-1 rounded border border-cyan-800/60">
                  ACT 03
                </span>
                <span className="text-xs text-slate-500 font-mono">Spatial Autocorrelation</span>
              </div>
              <h3 className="text-xl font-bold text-white mb-2">
                Tightening Spatial Autocorrelation & N₂O Spillovers
              </h3>
              <p className="text-sm text-slate-300 leading-relaxed mb-4">
                Global Moran's I climbed from <strong className="text-white">+0.255</strong> (1961) to <strong className="text-emerald-400">+0.729</strong> (2024). Agrifood emissions are no longer spatially isolated. Under the Spatial Durbin Model (SDM), synthetic N₂O fertilizer application induces cross-border spillovers (<strong className="text-cyan-400">+1.1046</strong>) more than double its direct domestic effect (<strong className="text-white">+0.5011</strong>).
              </p>
              <div className="p-3 bg-slate-950 rounded-xl border border-slate-800 text-xs text-slate-400">
                <strong className="text-slate-200">LISA 2024 Significance:</strong> 7 ASEAN economies constitute a contiguous <strong className="text-red-400">High-High</strong> hotspot, while the Philippines and Singapore exhibit <strong className="text-purple-400">Low-High</strong> spatial outlier status.
              </div>
            </div>
          </div>

          {/* Babak 4 */}
          <div className="p-6 rounded-2xl bg-slate-900/60 border border-slate-800 hover:border-slate-700 transition-all flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between mb-3">
                <span className="text-xs font-mono font-bold text-teal-400 bg-teal-950/60 px-2.5 py-1 rounded border border-teal-800/60">
                  ACT 04
                </span>
                <span className="text-xs text-slate-500 font-mono">Regional Policy Agenda</span>
              </div>
              <h3 className="text-xl font-bold text-white mb-2">
                Policy Imperatives: Regional Co-Governance Architecture
              </h3>
              <p className="text-sm text-slate-300 leading-relaxed mb-4">
                Because input spillovers and agricultural land pressures cascade across national boundaries, isolated domestic NDCs inevitably trigger *carbon leakage*. ASEAN requires harmonized agroecological input standards and integrated deforestation-free market compacts.
              </p>
              <div className="p-3 bg-slate-950 rounded-xl border border-slate-800 text-xs text-slate-400">
                <strong className="text-slate-200">Simulation Outcome:</strong> A 20% reduction in synthetic fertilizer across the Frontier cluster abates over 30 Mt CO₂eq annually via regional spatial multiplier dynamics.
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* 3. PORTAL NAVIGATION CARDS */}
      <section className="max-w-6xl mx-auto px-4">
        <div className="p-8 rounded-3xl bg-gradient-to-b from-slate-900 to-[#0b1220] border border-slate-800 shadow-2xl">
          <div className="max-w-3xl mb-8">
            <h3 className="text-2xl font-black text-white tracking-tight">
              Explore the GRAIN Platform Modules
            </h3>
            <p className="text-sm text-slate-400 mt-1">
              Select an analytical module to examine raw balanced panels, interactive cartography, econometric diagnostics, or run regional policy simulations.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
            <Link
              to="/clustering"
              className="p-5 rounded-2xl bg-slate-950/60 border border-slate-800 hover:border-emerald-500/50 hover:bg-slate-900/80 transition-all group"
            >
              <div className="w-10 h-10 rounded-xl bg-red-500/10 text-red-400 flex items-center justify-center mb-3 group-hover:scale-110 transition-transform">
                <MapPin className="w-5 h-5" />
              </div>
              <h4 className="font-bold text-white text-base group-hover:text-emerald-400 transition-colors">
                Thematic Maps & 5 Agrifood Clusters
              </h4>
              <p className="text-xs text-slate-400 mt-1 leading-relaxed">
                Interactive 3D/2D orbital maps, 5 agrifood typology profiles, and 44 Asia-Pacific economy audit tables.
              </p>
              <div className="mt-4 flex items-center gap-1 text-xs font-semibold text-emerald-400">
                <span>Launch Cluster Explorer</span>
                <ArrowRight className="w-3.5 h-3.5" />
              </div>
            </Link>

            <Link
              to="/spasial"
              className="p-5 rounded-2xl bg-slate-950/60 border border-slate-800 hover:border-cyan-500/50 hover:bg-slate-900/80 transition-all group"
            >
              <div className="w-10 h-10 rounded-xl bg-cyan-500/10 text-cyan-400 flex items-center justify-center mb-3 group-hover:scale-110 transition-transform">
                <Layers className="w-5 h-5" />
              </div>
              <h4 className="font-bold text-white text-base group-hover:text-cyan-400 transition-colors">
                Spatial Econometrics Command
              </h4>
              <p className="text-xs text-slate-400 mt-1 leading-relaxed">
                OLS vs SDM model selection (AIC 4,752.0), 64-year Moran's I trajectories, and LeSage–Pace decompositions.
              </p>
              <div className="mt-4 flex items-center gap-1 text-xs font-semibold text-cyan-400">
                <span>Launch Econometrics Suite</span>
                <ArrowRight className="w-3.5 h-3.5" />
              </div>
            </Link>

            <Link
              to="/simulator"
              className="p-5 rounded-2xl bg-slate-950/60 border border-slate-800 hover:border-amber-500/50 hover:bg-slate-900/80 transition-all group"
            >
              <div className="w-10 h-10 rounded-xl bg-amber-500/10 text-amber-400 flex items-center justify-center mb-3 group-hover:scale-110 transition-transform">
                <Sliders className="w-5 h-5" />
              </div>
              <h4 className="font-bold text-white text-base group-hover:text-amber-400 transition-colors">
                Regional Policy Simulator
              </h4>
              <p className="text-xs text-slate-400 mt-1 leading-relaxed">
                Simulate synthetic fertilizer efficiencies, forest moratoria, and compute cross-border multiplier spillovers.
              </p>
              <div className="mt-4 flex items-center gap-1 text-xs font-semibold text-amber-400">
                <span>Launch Policy Simulator</span>
                <ArrowRight className="w-3.5 h-3.5" />
              </div>
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
};
